# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'CardCheck' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CardCheck
  pod 'SDVersion', '~> 4.2'
  pod 'AFNetworking', '~> 3.0'

  target 'CardCheckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CardCheckUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
